sudo : false
langague : node_js
node_js:
- 'node'
branches : 
  only:
    -main
cache:
  directories:
    - node_modules
before_install:
  - npm update
install : 
  - npm install
script:
  -npm test
  -npm run coveralls